#!/bin/bash

mkdir jobs

for range in `ls | grep ^[0-9][0-9]\*-[0-9][0-9]\*\$`
do
	pwd=`pwd`
	abs="$pwd/$range"

	echo "#!/bin/bash" > jobs/align-$range
	echo "${HOME}/bin/xvfb-run -a ${HOME}/packages/Fiji.app/fiji-linux64 -Xms10g -Xmx10g -Ddir=$abs -Dfile=$abs/import.txt  -- --no-splash ${pwd}/import-and-align.bsh" >> jobs/align-$range
	chmod a+x jobs/align-$range
done

