#!/bin/bash

# Apply the accumulated rigid transformation to a series of pairwise aligned
# chunks and update heir joint bounding box.
#
# Call:
#       ./create-apply-aligned-overlapping-projects-job <file-list> <chunk-size>

mkdir -p jobs

n=`wc -l < ${1}`
mod=${2:-100}

pwd=`pwd`
abs="$pwd/$range"

echo "#!/bin/bash" > jobs/apply-aligned-overlapping-projects
echo "${HOME}/bin/xvfb-run -a ${HOME}/packages/Fiji.app/fiji-linux64 -Xms10g -Xmx10g -Ddir=${pwd} -Dstart=0 -Dend=$(($n-1)) -Doverlap=$(($mod/2)) -- --no-splash ${pwd}/apply-aligned-overlapping-projects.bsh" >> jobs/apply-aligned-overlapping-projects
chmod a+x jobs/apply-aligned-overlapping-projects

