#!/bin/bash

# Export overlapping chunks that were independently aligned with a
# transformation that is the linear interpolant of both independently
# estimated transformations in the overlapping range, weights run from 0-1
# across the range.
#
# Call:
#       ./create-export-job <file-list> [<chunk-size> <export-dir> <project-base-dir>]
# Defaults:
#   chunks-size:        100
#   export-dir:         $PWD
#   project-base-dir:   $PWD

if [ $# -lt 2 ]; then
    echo "Usage: $0 <file-list> [<chunk-size=100> <export-dir=$PWD> <project-base-dir=$PWD>]"
    exit 1
fi

n=`wc -l < ${1}`
mod=${2:-100}
exportDir="${3:-$PWD}"
projectBaseDir="${4:-$PWD}"

step=$(($mod/2))
first=0
last=$(($n-1))

mkdir -p jobs
mkdir -p export

#for i in `seq $first $step $(($last-3*$step))` 
for i in `seq $first $step $(($last-$step))` 
do
	range="$i-$(($i+3*$step-1))"
	range1="$i-$(($i+2*$step-1))"
	range2="$(($i+$step))-$(($i+3*$step-1))"
	job="jobs/export-project-intersection-$range"

	echo "#!/bin/bash" > $job
	echo "${HOME}/bin/xvfb-run -a ${HOME}/packages/Fiji.app/fiji-linux64 -Xms10g -Xmx10g -Ddir1=$projectBaseDir/$range1 -Ddir2=$projectBaseDir/$range2 -Dexport=$exportDir/export  -- --no-splash $projectBaseDir/open-and-export-project-intersection.bsh" >> $job
	chmod a+x $job
done

