#!/bin/bash

pwd="`pwd`"
export="$pwd/export"
cropdir="$export/crop"
scaledir="$export/scale"
jobs="$pwd/jobs"
logs="$jobs/log"
#nJobs=500
nJobs=10

mkdir -p "$scaledir"
mkdir -p "$cropdir"
mkdir -p "$jobs"
mkdir -p "$logs"

n=`find export/ -maxdepth 1 -not -type d -name '*tif' | wc -l`
tasksPerJob=$[$n/$nJobs]

j=1
k=0
script="$jobs/export-scale-crop-$k.job"
echo "#!/bin/bash" > "$script"

for file in `cd $export; ls | grep -P "\.tif$"`
do

   if [ $j -ge $tasksPerJob ]; then
	  chmod a+x "$script"
	  cd "$logs"
	  qsub -cwd $script # run previous job
	  cd "$pwd"

	  j=0
	  ((k++))

	  # get started on the next job
	  script="$jobs/export-scale-crop-$k.job"
	  echo "#!/bin/bash" > "$script"
   fi

	echo "convert $export/$file -resize 10% $scaledir/$file" >> "$script"
#	echo "convert $export/$file -crop 768x768+2900+2400 $export/crop1/$file" >> "$script"
#	echo "convert $export/$file -crop 768x768+1550+4500 $export/crop2/$file" >> "$script"
#	echo "convert $export/$file -crop 768x768+3970+5440 $export/crop/$file" >> "$script"
#	echo "convert $export/$file -crop 768x768+1400+4700 $export/crop/$file" >> "$script"
	echo "convert $export/$file -crop 2060x5120+3620+2220 $cropdir/$file" >> "$script"

	((j++))
done
cd "$pwd"

chmod a+x "$script"
qsub -cwd $script # run previous job
