#!/bin/bash

ranges=`ls | grep ^[0-9][0-9]\*-[0-9][0-9]\*\$ | sort -g`

pwd=`pwd`
mkdir -p $pwd/jobs/log
cd $pwd/jobs/log

for range in $ranges
do
	qsub -cwd -pe batch 4 $pwd/jobs/align-$range
done

cd $pwd
