#!/bin/bash

ranges=`ls | grep ^[0-9][0-9]\*-[0-9][0-9]\*\$ | sort -g`

pwd=`pwd`
mkdir -p $pwd/jobs/log
cd $pwd/jobs/log
submittedJobsFile="$pwd/subJobs.pae"

if [ -e $submittedJobsFile ]; then
    rm $submittedJobsFile
fi

for range in $ranges
do
    echo "submitting range: $range"
	qsub -cwd -V -pe batch 5 "$pwd/jobs/align-$range" >> $submittedJobsFile
done

cd $pwd
